version: "3.7"

services:
  postgresql:
    container_name: postgresql-birthday-bot
    restart: unless-stopped
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: birthday-bot
    volumes:
      - ./.docker/postgresql/data:/var/lib/postgresql/data